kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"apps/v1","kind":"Deployment","name":"open-webui"}]'
  name: chroma
  namespace: open-webui
  labels:
    app: chroma
    app.kubernetes.io/component: chroma
    app.kubernetes.io/instance: chroma
    app.kubernetes.io/name: chroma
    app.kubernetes.io/part-of: llm_serving
    app.openshift.io/runtime-namespace: open-webui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chroma
  template:
    metadata:
      labels:
        app: chroma
        deployment: chroma
    spec:
      containers:
        - name: chroma
          image: 'ghcr.io/chroma-core/chroma:latest'
          ports:
            - containerPort: 8000
              protocol: TCP
          resources:
            limits:
              cpu: '1'
              memory: '2Gi'
            requests:
              cpu: '0.2'
              memory: '1Gi'
          imagePullPolicy: IfNotPresent
          envFrom:
            - configMapRef:
                name: chroma-configmap
          volumeMounts:
            - name: chroma-volume
              mountPath: '/chroma/chroma'
      volumes:
      - name: chroma-volume
        persistentVolumeClaim:
          claimName: chroma-pvc                    
